kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            system-reserved: memory=2518Mi
    # add a mount from /path/to/my/files on the host to /files on the node
    extraMounts:
      - hostPath: /kubernetes-persistent-volume/redis
        containerPath: /kubernetes-persistent-volume/redis
